include/wx/pdfcolour.h
This makes it possible to include wx/pdfcolour.h (and, hence, wx/pdfdoc.h
which includes it) without having to include wx/gdicmn.h first.
=> Forward declare wxColourDatabase before using it in a header.

src/pdfdc29.inc
Map wxJOIN_XXX/wxCAP_XXX constants to the corresponding wxPDF_LINEJOIN/CAP ones.
=> Honour wxPen cap and join styles in the PDF output.

src/pdfdc29.inc
This is allowed by wxDC API and the null pointers should be simply ignored,
i.e. the corresponding values shouldn't be returned.
=> Don't crash in wxPdfDC::GetTextExtent() if x or y are null.

samples/pdfdc/printing.cpp, src/pdfdc29.inc, src/pdfprint.cpp
Mostly use wx{PEN,BRUSH}STYLE_XXX constants instead of just wxXXX but also
just drop some occurrences of wxSOLID which is the default style anyhow.
Also simplify the code slightly using wx{Pen,Brush}::IsNonTransparent() helper
function.
finally, use "do{Fill,Draw}" variable names consistently everywhere, instead
of "do_{brush,pen}" in a single place.
=> Avoid deprecation warnings when building with wxWidgets 3.1.

src/pdfdc29.inc
DoDrawRectangle() scales the coordinates passed to it, so don't pass it the
already scaled double PDF coordinates but the original unscaled wxCoord ones.
=> Fix using wrong coordinates when drawing monochrome bitmaps in wxPdfDC.

include/wx/pdfdc29.h, src/pdfdc29.inc
The changes here were done originally just because I was getting warnings each time when including `pdfdc.h` (which they fix), but they actually turn out to fix serious problems with drawing poly-polygons and splines which previously didn't work at all with wx3 as the methods that were supposed to be overridden actually were not as they didn't have the correct signature.
=> More fixes for wxWidgets 3.0 for wxPdfDCImpl

src/pdfdc29.inc, src/pdffontdatacore.cpp, src/pdffontdatatype0.cpp, src/pdffontparsertruetype.cpp, src/pdffontparsertype1.cpp, src/pdfkernel.cpp, src/pdfocg.cpp
The first patch is trivial, the second one a bit less so and, annoyingly, I don't really know how to test the changes. But hopefully they don't break anything, even if one of them completely removes the `familyName` variable which didn't seem to be used at all, so even though my patches shouldn't change the code behaviour, perhaps the code was wrong to begin with...
=> Fix harmless but annoying VC14 warnings

.travis.yml
Build the library only under Ubuntu Trusty using gcc for now.
---
I'd like to enable continuous integration for this project, to at least ensure that no stupid last minute changes break the build for now (in the future I'd like to add some real tests which would be executed as part of the build), especially if the changes are committed from MSW and so might not have been tested under Unix (of course, CI is not a replacement for testing, but better to have both...). If you haven't used Travis before, you can see how a typical build looks like [here](https://travis-ci.org/vadz/wxpdfdoc/jobs/190087447).
For this to work, you need to enable Travis for your repository at https://travis-ci.org/ (you will need to create/associate Travis account with your Github account, IIRC).
=> Add minimal Travis CI configuration file

.travis.yml
Test building with both wxWidgets 3.0 and 2.8 under Ubuntu Trusty.
---
Let's see if it works (and by "it" I mean both Travis integration, which should kick in automatically for this PR, and building with 2.8).
=> Add a build using wxWidgets 2.8 to Travis CI

.travis.yml, admin/travis/before_install.sh
Create a "before install" script to make it simpler to handle multiple
platforms in .travis.yml.
=> Add OS X build to Travis CI

Makefile.am, configure.ac
With these changes, running
~/src/wxpdfdoc/configure --host=i686-w64-mingw32 --with-wx-confi=~/build/wx/msw/wx-config
and then `make` works and produces apparently working MSW executables for the samples.
=> Fixes for MSW cross-compilation

configure.ac, include/wx/pdfdocdef.h
Use ELF visibility to not export everything from the library by default, but
only the symbols marked with WXDLLIMPEXP_PDFDOC. This should work, i.e. export
all the really required symbols, as it already does under MSW and it removes
more than a thousand symbols that should not be exported from the library.
=> Only export selected symbols from the library under Unix

Makefile.am, configure.ac, readme.md, wxpdfdoc.pc.in
This will allow to use it easily from the other Unix projects with the help of
PKG_CHECK_MODULES(), instead of having to check for it in a complicated way
involving using WX_LIKE_LIBNAME().
---
With this file, it's now possible to build the printing sample using a single command like this:
g++ printing.cpp `pkg-config --cflags --libs wxpdfdoc` `wx-config --cxxflags --libs std,richtext`
=> Add pkg-config data file for the library

.travis.yml, admin/travis/before_install.sh
Get wxMSW packages from a custom repository and test cross-building using
them.
WXGTK_PACKAGE was renamed to WX_PACKAGE as it can now also be set to
libwxmsw3.0-dev which is not really wxGTK.
=> Test cross-compilation to MSW on Travis CI too

configure.ac, src/pdffontmanager.cpp, wxpdfdoc.pc.in
This fixes static linking when using wxGTK3, as it doesn't depend on Fontconfig any longer, unlike wxGTK2, so we need to link with it explicitly.
=> Link with Fontconfig explicitly when needed

Makefile.am, admin/travis/before_install.sh
It is never necessary to link static libraries with anything and it was, in
fact, actively harmful instead of just useless, at least when cross-compiling
from Linux to macOS, as doing this resulted in completely bogus linker errors
about "file was built for archive which is not the architecture being linked"
(even though it was) and the library being just ignored, resulting in tons of
undefined symbol errors later.
Simply don't link the static library with anything to fix this (it's a pity
that libtool is not smart enough to only apply LIBADD to shared libraries).
=> Don't link the static library with wxWidgets libraries

admin/travis/before_install.sh
32 bit version is not available and not needed, but the updated Ubuntu VM used
by Travis seems to require it now, so explicitly tell it not to try to get it.
This should hopefully make MSW build on Travis CI work again.
=> Only download 64 bit versions of wxMSW packages in Travis script

include/wx/pdfdc.h, src/pdfdc28.inc, src/pdfdc29.inc
This mode preserve the size of the fonts in the wxPdfDC API as in the
wxPdfDocument API. However, it does not change the Y reference of texts
in wxPdfDC so that this continues to behave like all wxDC (this is
different with wxPDF_MAPMODESTYLE_PDF).
=> Added a new map mode style: wxPDF_MAPMODESTYLE_PDFFONTSCALE.

src/pdfgraphics.cpp
When I setup a pen with wxPENSTYLE_LONG_DASH, it is not cleared by wxPENSTYLE_SOLID because postscript remembers the last dash pattern so that when going back to solid, [ ] 0 d must be given instead of
nothing.
Here is a minimal example to reproduce the bug and here is a patch that fixes it.
[wxpdfdoc-sample.cpp.gz](https://github.com/utelle/wxpdfdoc/files/1433398/wxpdfdoc-sample.cpp.gz)
=> Fixed bug with dashes

src/pdffontparsertruetype.cpp
This static variable is never referred to in the source file. It causes a warning from g++ and clang.
=> Remove tableNamesDefault (unused).

src/pdfdc28.inc, src/pdfdc29.inc
This commit had, for some reason, disabled vertical coordinates
adjustment when outputting text via wxPdfDC, making it incompatible with
all the other wxDC implementations as the point passed to DrawText()
was used as the coordinate of the baseline of the text and not its top
left corner.
Whatever the original problem was, this fix is clearly wrong as it means
that a simple DrawText("Hello", 0, 0) doesn't show anything at all in
the generated PDF.
---
It took me a long time to realize why rendering using wxHTML on a `wxPdfDC` didn't work the same way as when previewing/rendering to the screen and the reason is that the text position wasn't handled correctly. The really annoying thing is that the original code clearly did it correctly, but then 69dcaa2e88cbfc004f6a422893490b11c86aae9e …
=> Revert 69dcaa2e88 "Added correct handling of map mode [...]"

include/wx/pdfprint.h
Override the new DoGetClippingRect() virtual method instead of the
DoGetClippingBox() to avoid deprecation warnings about using the latter.
Note that wxWidgets 3.1.2 is not released yet, this change avoids
warnings when using the latest wxWidgets master from Git (i.e. a version
including c5530b1abf36c652c29611c2ccb5a9d01305a3c1 commit).
---
This is just a trivial change to avoid a couple of warnings with the latest wxWidgets master.
Note that we don't need to call `UpdateBoundingBox()` in the new function, as this accessor doesn't change anything anyhow. In fact, the old one (`DoGetClippingBox()`) doesn't need it neither, but I decided not to remove it in the same PR.
=> Avoid deprecation warning for DoGetClippingBox() with wx 3.1.2+

src/pdfdc29.inc
Replace them with wxPENSTYLE_XXX equivalents preferred in wx 2.9 and
later.
This avoids a bunch of -Wenum-compare-switch clang warnings similar to
warning: comparison of two values with different enumeration types in
switch statement ('wxPenStyle' and 'wxDeprecatedGUIConstants')
=> Stop using deprecated pen style constants

include/wx/pdfdc29.h, include/wx/pdfdocument.h, src/pdfdc29.inc, src/pdfkernel.cpp
I'm forwarding this from https://github.com/vadz/wxpdfdoc/pull/2 as I think this is generally useful. In our use case, it results in significant speed up when generating text-heavy PDFs and while the exact amount will depend on the exact contents, I think it should help in just about all cases.
=> Speed up text drawing

Makefile.am, configure.ac
Sometimes, e.g. when building the library as a dependency of another
application for a CI build, just the library files themselves need to be
built and it's a waste of time to build the non-installable programs, so
allow disabling building them by using the corresponding --disable-xxx
options.
=> Add configure options to skip building samples/utilities

src/pdfdc28.inc, src/pdfdc29.inc
Don't set background mode to "solid" in wxPdfDCImpl constructor, this is
inconsistent with the standard wxDC classes, which use transparent
background by default.
Setting it to "solid" went unnoticed for a long time because background
mode was ignored anyhow, but became significant since support for it was
added in 4c54889a6213ab72e660e5a14823da2bf06b1d6c.
=> Use the transparent background mode by default

src/pdfdc29.inc
Since WX 2.9 we should use wxBRUSHSTYLE_TRANSPARENT and wxBRUSHSTYLE_SOLID
instead of wxTRANSPARENT and wxSOLID for the background mode.
But in the sample printing.cpp we should still use old constants to
support WX 2.8.
=> Use right constants in wxPdfDCImpl::SetBackgroundMode()

include/wx/pdfdc.h
Use it for wxPdfDCImpl::GetResolution() too, as this virtual function
exists (since a very long time) in the base wxDCImpl class too.
---
I'm not sure how did I manage to not notice this until now, but building with clang resulted in multiple instances of
```
In file included from $wxpdfdoc/samples/pdfdc/printing.cpp:45:
$wxpdfdoc/include/wx/pdfdc.h:83:7: warning: 'GetResolution' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
int GetResolution() const;
^
$wx/include/wx/dc.h:667:17: note: overridden virtual function is here
virtual int GetResolution() const
^
```
which are fixed by this trivial change.
=> Fix clang warning about inconsistent use of override

.gitignore, configure.ac, src/pdfdocument.cpp, src/pdffontdataopentype.cpp, src/pdffontdatatruetype.cpp, src/pdfkernel.cpp, src/pdfxml.cpp
There shouldn't be any real changes here, but please check b8be543adb33dc4ec78c2681806401097ace7a2f and 3af0b9284accc2ea05c90cc57ac2764a99920f48 just in case I misunderstood the real intention there.
Otherwise this is just a collection of fixes for the miscellaneous warnings that I saw while building my project using wxPdfDoc under Linux and MSW.
=> Miscellaneous warnings fixes

include/wx/pdfdocument.h, include/wx/pdfxml.h, src/pdfdocument.cpp, src/pdfform.cpp, src/pdfxml.cpp
This is an implementation of wxPdfTable::Write() which first finds page breaks, than draws on every page at first the background, than the border and at last the content.
So, the cell border is not overwritten by the background of a subsequent table cell.
The old WriteRow() is not used anymore but still available since it is part of the public interface of the class.
In wxPdfDocument a member has been added to save the height of the header on each page. This value is needed to calculate the page breaks.
=> refactoring of print table to not overwrite borders with background color
